### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by ghost** [Jaminima/Trade-Ogre-Bot#1]
when i goto run the autotrader.exe i get 
Hello World!
Unhandled exception. System.Exception: Must be authorized

**Comment by Jaminima** [comment]
Hi, a file should generate on first run which you need to put your login credentials inside of

**Comment by Jaminima** [comment]
Likely config.json

**Comment by ghost** [comment]
thank you, i edited config.json with my api keys but still the same error.

**Comment by Jaminima** [comment]
Hi did you place this file in bin/debug? If so try putting it in there! Failing that possibly putting the file in the solution directory.

**Comment by ghost** [comment]
tried to do both and still same error, this is out of my knowledge, was trying to see if i can do it! thank you for your time.
